### PR TITLE
8267536: Many tests fail on Windows because of recent jextract changes to CursorKind

### PR DESCRIPTION
**Pull request by sundararajana**
added all cursor attribute kinds from Index.h

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267536](https://bugs.openjdk.java.net/browse/JDK-8267536): Many tests fail on Windows because of recent jextract changes to CursorKind

### Reviewers
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-foreign pull/541/head:pull/541` \
`$ git checkout pull/541`

Update a local copy of the PR: \
`$ git checkout pull/541` \
`$ git pull https://git.openjdk.java.net/panama-foreign pull/541/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 541`

View PR using the GUI difftool: \
`$ git pr show -t 541`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-foreign/pull/541.diff">https://git.openjdk.java.net/panama-foreign/pull/541.diff</a>

</details>

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
LGTM

**Comment by sundararajana** [comment]
Thanks @JornVernee for running tests and samples on Windows

**Pull request closed without merging**
