### PR TITLE
8267504: jextract should report unsupported language and exit rather than generating partial nonworking code

### PR DESCRIPTION
**Pull request by sundararajana**
Piggybacking to remove unused code. Avoid hardcoding enum values - using generated code instead.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8267504](https://bugs.openjdk.java.net/browse/JDK-8267504): jextract should report unsupported language and exit rather than generating partial nonworking code

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-foreign pull/539/head:pull/539` \
`$ git checkout pull/539`

Update a local copy of the PR: \
`$ git checkout pull/539` \
`$ git pull https://git.openjdk.java.net/panama-foreign pull/539/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 539`

View PR using the GUI difftool: \
`$ git pr show -t 539`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-foreign/pull/539.diff">https://git.openjdk.java.net/panama-foreign/pull/539.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — COMMENTED** [review]
Looks good - I'm not sure I get the need for the full.symbol list

**Comment by sundararajana** [comment]
I wanted to save full symbols file if in case if we wanted to bring few more symbols from libclang in future.

**Review by mcimadamore — APPROVED** [review]
Looks good

**Pull request closed without merging**
