### PR TITLE
Investigate ways to make handoff-like operation more explicit (foreign-memacess edition)

### PR DESCRIPTION
**Pull request by mcimadamore**
This is a subset of the patch proposed here:
https://git.openjdk.java.net/panama-foreign/pull/361

I'd like to integrate the memory access bits first and then merge the changes into PR 361.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/panama-foreign pull/363/head:pull/363`
`$ git checkout pull/363`

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
Looks good. Though, I think we should mention somewhere on handoff/share/registerCleaner, or maybe on the class, that attachments, cleanup actions, and cleaners are transferred to the new segment when doing these operations.

**Comment by mcimadamore** [comment]
> Looks good. Though, I think we should mention somewhere on handoff/share/registerCleaner, or maybe on the class, that attachments, cleanup actions, and cleaners are transferred to the new segment when doing these operations.

Not sure I fully agree - in the sense that cleanupAction/attachment are no longer first class properties of the segment - as much as they are property of segments created unsafely.

For cleaner, it's a different story, I'll work on something.

**Comment by JornVernee** [comment]
> > Looks good. Though, I think we should mention somewhere on handoff/share/registerCleaner, or maybe on the class, that attachments, cleanup actions, and cleaners are transferred to the new segment when doing these operations.
> 
> Not sure I fully agree - in the sense that cleanupAction/attachment are no longer first class properties of the segment - as much as they are property of segments created unsafely.

Could also mention this on the asSegmentRestricted factory maybe?

**Review by JornVernee — APPROVED** [review]

**Pull request closed without merging**
