### PR TITLE
8264397: Use the blessed modifier order in jdk.incubator.foreign

### PR DESCRIPTION
**Pull request by alblue**
Let me know if this is the right branch to apply to; I can submit this change against a different branch if needed.

This replaces https://github.com/openjdk/jdk/pull/3253

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264397](https://bugs.openjdk.java.net/browse/JDK-8264397): Use the blessed modifier order in jdk.incubator.foreign

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-foreign pull/486/head:pull/486` \
`$ git checkout pull/486`

Update a local copy of the PR: \
`$ git checkout pull/486` \
`$ git pull https://git.openjdk.java.net/panama-foreign pull/486/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 486`

View PR using the GUI difftool: \
`$ git pr show -t 486`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-foreign/pull/486.diff">https://git.openjdk.java.net/panama-foreign/pull/486.diff</a>

</details>

### CODE REVIEW

**Comment by JornVernee** [comment]
This should go into the foreign-memaccess+abi branch instead.

**Comment by alblue** [comment]
Rebased change onto foreign-memaccess+abi and switched target branch in this PR

**Pull request closed without merging**
