### PR TITLE
Deduplicate layouts and simplify value layout implementations

### PR DESCRIPTION
**Pull request by minborg**
This PR proposes adding deduplication of the immutable value layout where one provides a value that is equal to the one already at hand. For example, `JAVA_INT.withBitAlignment(32)` will return the same object. There is no general caching mechanism that guarantees a layout will never repeat. 

Another part of this PR relates to simplifying value layouts so they only have a single constructor. This will reduce size slightly. Related to this is the replacement of certain magic numbers which are now represented by constants.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/panama-foreign pull/795/head:pull/795` \
`$ git checkout pull/795`

Update a local copy of the PR: \
`$ git checkout pull/795` \
`$ git pull https://git.openjdk.org/panama-foreign pull/795/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 795`

View PR using the GUI difftool: \
`$ git pr show -t 795`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/panama-foreign/pull/795.diff">https://git.openjdk.org/panama-foreign/pull/795.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — COMMENTED** [review]
Looks good. I'd suggest to split the part which uses constants for the sizes (which seems like a great idea) from the deduplication logic, which makes the code a bit more convoluted (perhaps some validation with jextract might be better, to see if deduplication of layouts bears any fruit).

**Comment by minborg** [comment]
Running a large number of tests and collecting deduce information reveals the following:

```
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep SAVED ORDER | wc -l
grep: ORDER: No such file or directory
       0
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep "SAVED ORDER" | wc -l
    9254
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep "CREATED ORDER" | wc -l
     842
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep "SAVED NAME" | wc -l
       0
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep "CREATED NAME" | wc -l
   34294
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep "SAVED BIT ALIGNMENT" | wc -l
     488
pminborg@pminborg-mac minborg-panama % cat /Users/pminborg/dev/minborg-panama/build/macosx-aarch64/test-support/jtreg_open_test_jdk_java_foreign/java/foreign/*.jtr | grep "CREATED BIT ALIGNMENT" | wc -l
     969
```

image

NOTE: This is for the total number of objects and not retained objects.

So, this indicates deduplicating name would provide next to zero benefit whereas deduplicating byte order has a much better potential.

**Comment by minborg** [comment]
Here is a run with jextract using the zstd lib:

  | Building jextract |   | Running jextract zstd |   | Runnig zstd
-- | -- | -- | -- | -- | --
created name | 250 |   | 315 |   | 0
saved name | 0 |   | 0 |   | 0
created bit alignment | 13 |   | 13 |   | 7
saved bit alignment | 36 |   | 247 |   | 1
created order | 0 |   | 0 |   | 0
saved order | 0 |   | 0 |   | 1

Again, deduplicating names proves pointless.

**Comment by minborg** [comment]
The PR is more aimed at cases where there is something like this:

```
private static final MY_INT = JAVA_INT.withOrder(ByteOrder.LITTLE_ENDIAN);
private static final OTHER_INT = JAVA_INT.withBitAlignment(32);
```

I am happy to close this PR if the quorum is this would provide relatively little benefit compared to the added complexity.

**Comment by mcimadamore** [comment]
> The PR is more aimed at cases where there is something like this:
> 
> ```
> private static final MY_INT = JAVA_INT.withOrder(ByteOrder.LITTLE_ENDIAN);
> private static final OTHER_INT = JAVA_INT.withBitAlignment(32);
> ```
> 
> I am happy to close this PR if the quorum is this would provide relatively little benefit compared to the added complexity.

In my experience, the code above is not very idiomatic, so I'd be for closing the PR until some evidence points otherwise. The data you have collected on jextract is interesting (thanks!), in the sense that running the generated bindings has the characteristics I would expect, but it seems like jextract itself (when running) is being a bit wild when it comes to layout creation (which might or might not be an issue, I'd have to look more at the code).

**Comment by minborg** [comment]
I am closing this PR now. We could always come back if duplicate instances becomes a problem. Thanks for the feedback on this PR.

**Pull request closed without merging**
