### PR TITLE
8265211: Print specific error message when an option parsing error occurs

### PR DESCRIPTION
**Pull request by JornVernee**
Hi,

This patch makes jextract print a more specific error message when an option parsing error occurs, where currently only the help message is printed.

For instance, when using an unrecognized option `-o` it will print

```
OPTION ERROR: o is not a recognized option
```

Or when specifying multiple header files

```
OPTION ERROR: Expected 1 header file, not 3
```

Thanks,
Jorn

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265211](https://bugs.openjdk.java.net/browse/JDK-8265211): Print specific error message when an option parsing error occurs

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/panama-foreign pull/500/head:pull/500` \
`$ git checkout pull/500`

Update a local copy of the PR: \
`$ git checkout pull/500` \
`$ git pull https://git.openjdk.java.net/panama-foreign pull/500/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 500`

View PR using the GUI difftool: \
`$ git pr show -t 500`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/panama-foreign/pull/500.diff">https://git.openjdk.java.net/panama-foreign/pull/500.diff</a>

</details>

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
As discussed offline, might be helpful to print help from `printOptonError` anyway.

**Comment by JornVernee** [comment]
@mcimadamore The help message is quite noisy because it's so large, I'm also worried that the error message will get lost in the noise. It's easy enough to re-run jextract with -h or --help to get the help message, if that is really wanted, so I'd prefer to leave it like this.

Though, I wouldn't be opposed to adding something like:

```
Use -h or --help for help
```

WDYT?

**Comment by mcimadamore** [comment]
> @mcimadamore The help message is quite noisy because it's so large

True - I also checked with other launchers:

```
$ java -f
Unrecognized option: -f
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

$ javac -f
error: invalid flag: -f
Usage: javac <options> <source files>
use --help for a list of possible options

```

Of theses, I think javac gets it right.

**Comment by JornVernee** [comment]
Okay, I agree, I'll follow what javac does.

**Comment by JornVernee** [comment]
I've updated the error message to also print usage information and a hint about using `--help`. Now, when an incorrect option is used, the following is printed:

```
$ jextract -f
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jextract
OPTION ERROR: f is not a recognized option
Usage: jextract <options> [--] <header file>
Use --help for a list of possible options
```

**Review by mcimadamore — APPROVED** [review]
Looks good!

**Pull request closed without merging**
