### PR TITLE
8253419: jextract should generate RuntimeHelper as a package private class

### PR DESCRIPTION
**Pull request by sundararajana**
Generated RuntimeHelper.java is package private now.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253419](https://bugs.openjdk.java.net/browse/JDK-8253419): jextract should generate RuntimeHelper as a package private class

### Reviewers
 * [Maurizio Cimadamore](https://openjdk.java.net/census#mcimadamore) (@mcimadamore - Committer) ⚠️ Review applies to d1f53919654960e07305cdf8373aee00bc1c91b2
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/panama-foreign pull/347/head:pull/347`
`$ git checkout pull/347`

### CODE REVIEW

**Review by mcimadamore — APPROVED** [review]
Looks good - do we also want to check the libclang implementation inside jextract - and rectify the RuntimeHelper in there?

**Review by JornVernee — APPROVED** [review]
Can nonCloseableNonTransferableSegment, nonCloseableSegment, and asArrayRestricted be made `private` as well? I don't think they are used outside of RuntimeHelper right?

**Comment by sundararajana** [comment]
> Looks good - do we also want to check the libclang implementation inside jextract - and rectify the RuntimeHelper in there?

Yes. That has to be sync'ed. Will do that

**Comment by sundararajana** [comment]
> Can nonCloseableNonTransferableSegment, nonCloseableSegment, and asArrayRestricted be made `private` as well? I don't think they are used outside of RuntimeHelper right?

nonCloseableNonTransferableSegment and asArrayRestricted are used in generated struct classes (StructBuilder). Will check  about nonCloseableSegment (and if not used outside, will make it private)

**Review by JornVernee — APPROVED** [review]

**Pull request closed without merging**
